In [1]:
import numpy as np

## Vector creation

#### Based on the shape of the array

In [3]:
a = np.zeros(4); print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [0. 0. 0. 0.], a shape = (4,), a data type = float64


In [4]:
a = np.zeros((4,));print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [0. 0. 0. 0.], a shape = (4,), a data type = float64


In [5]:
a = np.random.random_sample(4);print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [0.05540965 0.85018351 0.51256306 0.99403639], a shape = (4,), a data type = float64


#### Methods that do not take shape as an input

In [11]:
a = np.arange(4);print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [0 1 2 3], a shape = (4,), a data type = int64


In [12]:
a = np.arange(4.);print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [0. 1. 2. 3.], a shape = (4,), a data type = float64


In [13]:
a = np.random.rand(4);print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [0.74279917 0.82716284 0.37284062 0.07386728], a shape = (4,), a data type = float64


#### Values can be specified manually

In [14]:
a = np.array([1,2,3.3,4.5]);print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [1.  2.  3.3 4.5], a shape = (4,), a data type = float64


## Operations

**Indexing** refering to an element of an array

In [16]:
a = np.arange(10); print(a)
print(f"a[2] is {a[2]}, and its shape is {a[2].shape}")

[0 1 2 3 4 5 6 7 8 9]
a[2] is 2, and its shape is ()


In [20]:
print(f"a[-1] is {a[-1]}, and a[-3] is {a[-3]}")

a[-1] is 9, and a[-3] is 7


In [24]:
#index must be within the range of array
try:
    c = a[16]
except Exception as e:
    print("Error message: ")
    print(e)

Error message: 
index 16 is out of bounds for axis 0 with size 10


**Slicing** Get access to a portion of the array `(start:stop:step)`

In [5]:
a = np.arange(10); print(a)
print(f"a is {a}, and its shape is {a.shape}")
print(f"a[1:4] is {a[1:4]}, and its shape is {a[1:4].shape}")
print(f"a[5:] is {a[5:]}, and its shape is {a[5:].shape}")
print(f"a[-2:] is {a[-2:]}, and its shape is {a[-2:].shape}")
print(f"a[:] is {a[:]}, and its shape is {a[:].shape}")

[0 1 2 3 4 5 6 7 8 9]
a is [0 1 2 3 4 5 6 7 8 9], and its shape is (10,)
a[1:4] is [1 2 3], and its shape is (3,)
a[5:] is [5 6 7 8 9], and its shape is (5,)
a[-2:] is [8 9], and its shape is (2,)
a[:] is [0 1 2 3 4 5 6 7 8 9], and its shape is (10,)


**Single vector operation**

In [6]:
b = -a ; print(f"b is -a {-a}, and its shape is {b.shape}")
b = np.sum(a) ; print(f"b is a.sum {np.sum(a)}, and its shape is {b.shape}")
b = np.mean(a) ; print(f"b is a.mean {np.mean(a)}, and its shape is {b.shape}")
b = a**2 ; print(f"b is a**2 {a**2}, and its shape is {b.shape}")
b = np.square(a); print(f"b is a-squared {np.square(a)}, and its shape is {b.shape} ")

b is -a [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9], and its shape is (10,)
b is a.sum 45, and its shape is ()
b is a.mean 4.5, and its shape is ()
b is a**2 [ 0  1  4  9 16 25 36 49 64 81], and its shape is (10,)
b is a-squared [ 0  1  4  9 16 25 36 49 64 81], and its shape is (10,) 


**Vector vector operation**

In [32]:
a = np.array([1,2,3,4]);b = np.array([5,6,7,8])

In [33]:
c = a+b ; print(f"a+b is {c}, its shape is {c.shape}")
d = np.dot(a,b) ; print(f"a.b is {d}, its shape is {d.shape}")

a+b is [ 6  8 10 12], its shape is (4,)
a.b is 70, its shape is ()


## Matrices

In [36]:
a = np.zeros((1, 5));print(f"a shape = {a.shape}, a = {a}")                     
a = np.zeros((2, 1));print(f"a shape = {a.shape}, a = {a}") 
a = np.random.random_sample((1, 1));print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.11471468]]


In [37]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [38]:
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]


In [15]:
s = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[2],[3],[4]])
m = np.matmul(s,d)
print(f"matrix multiplication of\n{s} \nand \n{d}\nwould be \n{m}")

matrix multiplication of
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
and 
[[2]
 [3]
 [4]]
would be 
[[20]
 [47]
 [74]]


## Linear Algebra

In [3]:
a = np.arange(9); b = a.reshape((-1,3))
print(f"b is \n {b}")

b is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
# normalizing by row
b_norm1 = np.linalg.norm(b, ord=1,axis=1, keepdims=True)
print(f" b_norm1 is \n {b_norm1}")
b/b_norm1

 b_norm1 is 
 [[ 3.]
 [12.]
 [21.]]


array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667],
       [0.28571429, 0.33333333, 0.38095238]])

In [15]:
# normalizing by row
b_norm1 = np.linalg.norm(b, ord=1,axis=0)
print(f" b_norm1 is \n {b_norm1}")
b/b_norm1

 b_norm1 is 
 [ 9. 12. 15.]


array([[0.        , 0.08333333, 0.13333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.58333333, 0.53333333]])

In [16]:
b_norm2 = np.linalg.norm(b, ord=2,axis=0)
print(f" b_norm2 is \n {b_norm2}")

 b_norm2 is 
 [6.70820393 8.1240384  9.64365076]
